// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv`

interface CloudflareEnv {
	NEXT_PUBLIC_APP_URL: "https://telecom-ims.pages.dev";
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
